### ISSUE TITLE
Update base Ubuntu Image

### ISSUE THREAD

**Issue by Faeranne** [evq/imx28-buildroot#1]
The currently used Ubuntu image (13.10) fails on apt-get update due to being EOL and not directly available on the ubuntu site.

**Comment by evq** [comment]
Hey @mrmakeit,

This docker image is based on the instructions found [here,](https://community.freescale.com/docs/DOC-98910) I am not sure if they will work on newer releases. If you would like to test switching the base image and updating the Dockerfile as needed I would gladly take your PR.

As for a stopgap solution, DigitalOcean provides package mirrors for EOLed ubuntu releases; I have created a branch which uses these. Please let me know if this works for you and I will merge it to master.

81437f7ebeb53364258ed402ad14c264f514c492

**Comment by evq** [comment]
#2 Fixes this as confirmed by @cabernar and myself. Thanks!
